services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  ngrok:
    build: .
    command: >
      sh -c "
        ngrok config add-authtoken $$NGROK_AUTHTOKEN &&
        ./start-ngrok.sh
      "
    ports:
      - "4040:4040"
    env_file:
      - .env
    volumes:
      - ngrok-data:/ngrok-data

  library_service:
    build: .
    entrypoint: ./entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8100
    volumes:
      - .:/app
      - ngrok-data:/ngrok-data
    ports:
      - "8100:8100"
    depends_on:
      - redis
    env_file:
      - .env

  celery:
    build: .
    entrypoint: ./entrypoint.sh
    command: celery -A library_service worker --loglevel=info
    volumes:
      - .:/app
      - ngrok-data:/ngrok-data
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    entrypoint: ./entrypoint.sh
    command: celery -A library_service beat --loglevel=info
    volumes:
      - .:/app
      - ngrok-data:/ngrok-data
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  ngrok-data: